files/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('victoria.urls'))
]

victoria/urls.py
from django.urls import path
from victoria import views as victoria_views


app_name = 'victoria'
urlpatterns = [
    path('', victoria_views.index, name="index"),
    path('reservas/', victoria_views.reservas, name='reservas'),
    path('reservas/availability/', victoria_views.availability, name='availability'),
    path('reservas/make', victoria_views.make_reservation, name='make'),
]

victoria/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import datetime as dt


class Reserva(models.Model):

    date = models.DateField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    up_to_date = models.BooleanField(
        default=True, verbose_name='Próximas fechas')

    owner = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='reservation')

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return f'Dueño: {self.owner}'

    def get_absolute_url(self):
        return reverse('victoria:availability',
                       args=[self.date])

    def get_reservations_by_date(self, input_date):
        dates = Reserva.objects.filter(date=input_date)
        return dates

    def make_res(self, reserva):
        if not reserva:
            return 2
        else:
            date = reserva.date
            apertura = dt.time(9, 0, 0)
            cierre = dt.time(21, 0, 0)
            midnight = dt.time(0, 0)
            user_prop = User.objects.get(pk=1)

            today_res = [i for i in Reserva.objects.filter(date=date)]
            r1 = Reserva(owner=user_prop, check_in=midnight,
                         check_out=apertura, date=date)
            r2 = Reserva(owner=user_prop, check_in=cierre,
                         check_out=midnight, date=date)
            today_res.insert(0, r1)
            today_res.append(r2)

            for todayRes in today_res:
                index = today_res.index(todayRes)
                elif reserva.check_in > todayRes.check_out and reserva.check_out < today_res[(index) + 1].check_in:
                    reserva.save()
                else:
                    pass
            try:
                check_res = Reserva.objects.get(id=reserva.id)
                return 0
            except self.model.DoesNotExist:
                return 1

victoria/forms.py
from django import forms
from .models import Reserva
import datetime


class CheckReservationForm(forms.Form):
    date = forms.DateField(label="Date", initial=datetime.date.today, widget=forms.SelectDateWidget)

class MakeReservationForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields = ['date', 'check_in', 'check_out']

victoria/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
import datetime
from .models import Reserva
from .forms import CheckReservationForm, MakeReservationForm
from django.contrib.auth.admin import User


def index(request):
    return render(request, 'victoria/index.html')


def reservas(request):
    reservas = Reserva.objects.all()
    context = {'reservas': reservas}
    return render(request, 'victoria/reservas.html', context)


def availability(request):
    form = CheckReservationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data.get('date')
            reservas = Reserva.objects.filter(date=cd)
            form = CheckReservationForm()
            context = {
                'reservas': reservas,
                'form': form
            }
            return render(request, 'victoria/daylist.html', context)
    return render(request, 'victoria/res_form.html', {'form': form})


def prueba(request):
    reservas = Reserva.objects.filter(date=request.POST['date'])
    context = {
        'reservas': reservas,
    }

    return render(request, 'victoria/availability.html', context)

def make_reservation(request):

    apertura = datetime.time(hour=9, second=0, microsecond=0)
    cierre = datetime.time(hour=21, second=0, microsecond=0)

    form = MakeReservationForm(request.POST or None) #It's a modelForm
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data
            print(cd)
            cd_ci = cd.get('check_in')
            cd_co = cd.get('check_out')
            cd_date = cd.get('date')
            owner = User.objects.get(pk=1)
            if cd_ci > apertura and cd_co < cierre:
                reservas = Reserva.objects.filter(date=cd_date)
                Reserva(owner=owner, date=cd_date, check_out=apertura)
                Reserva(owner=owner, date=cd_date, check_in=cierre)
                for i in range(len(reservas)):
                    if reservas[i].check_out < cd_ci and reservas[i + 1].check_in > cd_co:
                        new_res = Reserva(owner=owner, date=cd_date, check_in=cd_ci, check_out=cd_co)
                        new_res.save()
                        context = {
                            'new_res': new_res,
                        }
                        return render(request, 'victoria/completed.html', context)
    else:
        return render(request, 'victoria/make.html', {'form': form})

victoria/templates/victoria/availability.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reservas filtradas</title>
{% endblock title %}

{% block body %}
<main>
    <section>
        {% for reserva in reservas %}
        <p> {{ reserva }} </p>
        {% endfor %}
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/completed.html
{% extends 'victoria/layout.html' %}

<h1>Gracias :D</h1>
<p>Hemos reservado tu espacio con éxito!</p>

victoria/templates/victoria/daylist.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reservas filtradas</title>
{% endblock title %}

{% block body %}
<main>
    <section>
        <form action="{% url 'victoria:availability' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    </section>

    <section>
        {% for reserva in reservas %}
        <h3> Reserva de {{ reserva.owner }} </h3>
        <p>Para el {{reserva.date.day}} del {{ reserva.date.month }}</p>
        <h6>de {{reserva.check_in}} a {{reserva.check_out}}</h6>
        {% endfor %}
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/index.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Home</title>
<style>
    #main-c {
        margin-top: 15px;
    }
</style>
{% endblock title %}


{% block body %}
<main class="container" id="main-c">
    <section class="main-section">
        <div class="row">
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Reservaciones por fecha.</h5>
                        <p class="card-text">Obtén las reservas del día.</p>
                        <a href="{% url 'victoria:availability' %}" class="btn btn-primary">Obtener</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Todas las reservaciones.</h5>
                        <p class="card-text">Obtén la lista completa.</p>
                        <a href="{% url 'victoria:reservas' %}" class="btn btn-primary">Obtener</a>
                    </div>
                </div>
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    {% block body %}
    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</body>

</html>

victoria/templates/victoria/make.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reserva tu espacio :)</title>
{% endblock title %}

{% block body %}
<main>
    <section>
        <div class="form-group">
            <form action="{% url 'victoria:make' %}" method="POST">
                {% csrf_token %}
                {{ form.as_table }}
                <input type="submit" value="Submit">
            </form>
        </div>
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/prueba.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reservas filtradas</title>
{% endblock title %}

{% block body %}
<main>
    <section>
        {% for reserva in reservas %}
        <p> {{ reserva }} </p>
        {% endfor %}
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/res_form.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reservas - Crear reserva</title>
{% endblock title %}

{% block body %}
<main>
    <section>
            <form action="{% url 'victoria:availability' %}" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Submit">
            </form>
    </section>
</main>
{% endblock body %}

victoria/templates/victoria/reservas.html
{% extends 'victoria/layout.html' %}

{% block title %}
<title>Reservas</title>
{% endblock title %}

{% block body %}
<main>
    <section>
        {% for reserva in reservas %}
        <h3>Esta reserva pertenece a {{ reserva.owner }}.</h3>
        <p>Para el {{ reserva.date.day }} del {{ reserva.date.month }}.</p>
        <p>De {{ reserva.check_in }} a {{ reserva.check_out }} </p>
        {% endfor %}
    </section>
</main>
{% endblock body %}